import { z } from 'zod';

/**
 * Chronicle Metadata Schema
 * 
 * YAML frontmatter for Chronicle chapters
 * Validates: date, chapterId, participants, sessionType, timestamps
 */
export const ChronicleMetadataSchema = z.object({
  // Date in YYYY-MM-DD format
  date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'Date must be in YYYY-MM-DD format'),
  
  // Chapter ID format: YYYY-MM-DD-chapter-NNN
  chapterId: z.string().regex(
    /^\d{4}-\d{2}-\d{2}-chapter-\d{3}$/,
    'Chapter ID must be in format: YYYY-MM-DD-chapter-NNN'
  ),
  
  // Participants in the session
  participants: z.array(z.string()).min(1, 'At least one participant required'),
  
  // Session type: general, ubik, axiom
  sessionType: z.enum(['general', 'ubik', 'axiom'], {
    errorMap: () => ({ message: 'Session type must be: general, ubik, or axiom' })
  }),
  
  // ISO 8601 timestamps
  startTime: z.string().datetime({ message: 'Start time must be ISO 8601 format' }),
  endTime: z.string().datetime({ message: 'End time must be ISO 8601 format' }),
  
  // Optional metadata
  tags: z.array(z.string()).optional(),
  summary: z.string().optional(),
  messageCount: z.coerce.number().int().positive().optional(),
});

export type ChronicleMetadata = z.infer<typeof ChronicleMetadataSchema>;

/**
 * Chronicle Content Schema
 * 
 * Markdown content sections for Chronicle chapters
 */
export const ChronicleContentSchema = z.object({
  // Chapter summary (generated by LLM)
  summary: z.string().min(1, 'Summary is required'),
  
  // Dialogue messages (markdown formatted)
  dialogue: z.string().min(1, 'Dialogue content is required'),
  
  // Extracted truths (facts discovered in session)
  truths: z.array(z.string()).default([]),
  
  // Key insights (high-level takeaways)
  insights: z.array(z.string()).default([]),
  
  // Tools created during session (autopoiesis)
  toolsCreated: z.array(z.string()).default([]),
  
  // Decisions made
  decisions: z.array(z.string()).default([]),
});

export type ChronicleContent = z.infer<typeof ChronicleContentSchema>;

/**
 * Chronicle Chapter Schema
 * 
 * Complete Chronicle chapter (metadata + content)
 */
export const ChronicleChapterSchema = z.object({
  metadata: ChronicleMetadataSchema,
  content: ChronicleContentSchema,
});

export type ChronicleChapter = z.infer<typeof ChronicleChapterSchema>;

/**
 * Chronicle Directory Structure
 * 
 * Defines the file organization for Chronicle storage
 * Supports CHRONICLE_ROOT env var for test isolation
 */
function getChronicleRoot(): string {
  return process.env.CHRONICLE_ROOT || 'data/chronicle';
}

/**
 * Get Chronicle directory path based on session type
 */
export function getChronicleDirectory(sessionType: ChronicleMetadata['sessionType']): string {
  return `${getChronicleRoot()}/chip/${sessionType}`;
}

/**
 * Get Chronicle file path for a chapter
 */
export function getChronicleFilePath(chapterId: string, sessionType: ChronicleMetadata['sessionType']): string {
  const directory = getChronicleDirectory(sessionType);
  return `${directory}/${chapterId}.md`;
}

/**
 * Generate unique chapter ID
 * Format: YYYY-MM-DD-chapter-NNN
 */
export function generateChapterId(date: string, sequenceNumber: number): string {
  const paddedNumber = sequenceNumber.toString().padStart(3, '0');
  return `${date}-chapter-${paddedNumber}`;
}

/**
 * Parse chapter ID to extract date and sequence number
 */
export function parseChapterId(chapterId: string): { date: string; sequenceNumber: number } | null {
  const match = chapterId.match(/^(\d{4}-\d{2}-\d{2})-chapter-(\d{3})$/);
  if (!match) return null;
  
  return {
    date: match[1],
    sequenceNumber: parseInt(match[2], 10),
  };
}

/**
 * Validation helper: Check if date is valid YYYY-MM-DD
 */
export function isValidDate(dateString: string): boolean {
  const match = dateString.match(/^(\d{4})-(\d{2})-(\d{2})$/);
  if (!match) return false;
  
  const [, year, month, day] = match;
  const date = new Date(`${year}-${month}-${day}`);
  
  return (
    date.getFullYear() === parseInt(year, 10) &&
    date.getMonth() + 1 === parseInt(month, 10) &&
    date.getDate() === parseInt(day, 10)
  );
}

/**
 * Validation helper: Check if timestamp is valid ISO 8601
 */
export function isValidISO8601(timestamp: string): boolean {
  try {
    const date = new Date(timestamp);
    return date.toISOString() === timestamp;
  } catch {
    return false;
  }
}
